//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_vanzare_flori
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Client> t_Client { get; set; }
        public virtual DbSet<t_Culoare> t_Culoare { get; set; }
        public virtual DbSet<t_CuloareFloare> t_CuloareFloare { get; set; }
        public virtual DbSet<t_DetaliiFactura> t_DetaliiFactura { get; set; }
        public virtual DbSet<t_DetaliiFloare> t_DetaliiFloare { get; set; }
        public virtual DbSet<t_Factura> t_Factura { get; set; }
        public virtual DbSet<t_FloarePlantata> t_FloarePlantata { get; set; }
        public virtual DbSet<t_Parfum> t_Parfum { get; set; }
        public virtual DbSet<t_ParfumFloare> t_ParfumFloare { get; set; }
        public virtual DbSet<t_Perioada> t_Perioada { get; set; }
        public virtual DbSet<t_PerioadaInflorire> t_PerioadaInflorire { get; set; }
        public virtual DbSet<t_Parcela> t_Parcela { get; set; }
    }
}
