//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_vanzare_flori
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CuloareFloare
    {
        public int ID_CuloareFloare { get; set; }
        public int ID_FloarePlantata { get; set; }
        public int ID_Culoare { get; set; }
    
        public virtual t_Culoare t_Culoare { get; set; }
        public virtual t_FloarePlantata t_FloarePlantata { get; set; }
    }
}
