//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_vanzare_flori
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DetaliiFloare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_DetaliiFloare()
        {
            this.t_FloarePlantata = new HashSet<t_FloarePlantata>();
        }
    
        public int ID_DetaliiFloare { get; set; }
        public string NumeFloare { get; set; }
        public string Clasificare { get; set; }
        public string Origine { get; set; }
        public string Soi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_FloarePlantata> t_FloarePlantata { get; set; }
    }
}
