//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_vanzare_flori
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Factura()
        {
            this.t_DetaliiFactura = new HashSet<t_DetaliiFactura>();
        }
    
        public int ID_Factura { get; set; }
        public int ID_Client { get; set; }
        public System.DateTime DataFacturare { get; set; }
    
        public virtual t_Client t_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_DetaliiFactura> t_DetaliiFactura { get; set; }
    }
}
