//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_vanzare_flori
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_FloarePlantata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_FloarePlantata()
        {
            this.t_CuloareFloare = new HashSet<t_CuloareFloare>();
            this.t_DetaliiFactura = new HashSet<t_DetaliiFactura>();
            this.t_ParfumFloare = new HashSet<t_ParfumFloare>();
            this.t_PerioadaInflorire = new HashSet<t_PerioadaInflorire>();
        }
    
        public int ID_FloarePlantata { get; set; }
        public int ID_DetaliiFloare { get; set; }
        public byte[] Imagine { get; set; }
        public int pozX { get; set; }
        public int pozY { get; set; }
        public int NumarParcela { get; set; }
        public string FormaFloare { get; set; }
        public int Inaltime { get; set; }
        public string Descriere { get; set; }
        public bool Valabila { get; set; }
        public System.DateTime DataPlantare { get; set; }
        public double PretAchizitie { get; set; }
        public double PretVanzare { get; set; }
        public bool Pierduta { get; set; }
        public string Hibridizator { get; set; }
        public Nullable<System.DateTime> DataPierdere { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_CuloareFloare> t_CuloareFloare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_DetaliiFactura> t_DetaliiFactura { get; set; }
        public virtual t_DetaliiFloare t_DetaliiFloare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_ParfumFloare> t_ParfumFloare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_PerioadaInflorire> t_PerioadaInflorire { get; set; }
    }
}
