//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_vanzare_flori
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Parcela
    {
        public int ID_Parcela { get; set; }
        public int NumarParcela { get; set; }
        public int NumarLinii { get; set; }
        public int NumarColoane { get; set; }
    }
}
